# Font configuration for Source Code Pro
[font]
  size = 12

  # Normal style
  [font.normal]
  family = "Source Code Pro"
  style = "Regular"

  # Bold style
  [font.bold]
  family = "Source Code Pro"
  style = "Bold"

  # Italic style
  [font.italic]
  family = "Source Code Pro"
  style = "Italic"

  # Bold Italic style
  [font.bold_italic]
  family = "Source Code Pro"
  style = "Bold Italic"

# Additional font settings
